config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'dashboard#index'

  devise_for :companies
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :game_sessions, only: [:show] do
    member do
      get '/players_count', to: 'game_sessions#players_count', as: :players_count
      get '/players_ordered', to: 'game_sessions#players_ordered', as: :players_ordered
    end
  end
  resources :players, only: [:show, :edit, :update] do
    resources :questions, only: [:show] do
      get '/countdown', to: 'questions#countdown', as: :countdown
      resources :answers, only: :create
    end
  end

  mount Attachinary::Engine => "/attachinary"
  Rails.application.routes.draw do
  # # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/game_session.rb
class GameSession < ApplicationRecord

  has_many :players
  belongs_to :company
  belongs_to :seance
  belongs_to :game
  enum status: {
    pending: 0,
    active: 1,
    finished: 2,
    closed: 3,
  }
  after_create :enqueue_job_opener
  before_save :initialize_gs

  def enqueue_job_opener
    ActivateGameSessionJob.set(wait_until: starting_at).perform_later(id)
  end

  def initialize_gs
    self.starting_at = start_at
    self.ending_at = end_at
    self.duration = duration

    if starting_at.future?
      self.status = :pending
    end
  end

  def calculate_ranking
    players_ordered = self.players.order(score: :desc, time_taken: :asc)
    i = 1
    players_ordered.each do |player|
      player.ranking = i
      i += 1
      player.save(validate: false)
    end
  end

  def calculate_winners
    self.players.update(winner: false)
    winners = self.players.where.not(email: nil).order(ranking: :asc).first(3)
    winners.each do |player|
      player.winner = true
      player.save
    end
  end

  def count_unsigned_players
    self.players.where(email: nil).count
  end

  def count_signed_players
    self.players.where.not(email: nil).count
  end

  # private

  def duration
    if !game.questions.nil?
      duration = 0
      game.questions.each do |question|
        duration += question.duration
      end
    end
    duration
  end

  def start_at
    seance.start_at + (offset_start || 0).seconds
  end

  def end_at
     start_at + duration + (offset_end || 0).seconds
  end
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  before_action :set_game_session, only: [:show, :check_player_token, :players_count, :players_ordered]
  before_action :disable_nav_footer

  def show
    @seance = @game_session.seance

    check_player_token

    @players = @game_session.players
    @players_count = @players.count

    @players_ordered = @game_session.players.order(ranking: :asc)
    @winners = @players_ordered.where(winner: true)
    @question = Question.new(game: @game_session.game)

    # Rails.logger.debug "GS-DEBUG id=#{@game_session.id} status is now #{@game_session.status}!"
  end

  def players_count
    @players_count = @game_session.players.count + "<br/><label>joueurs</label>"
  end

  def players_ordered
    @game_session.calculate_ranking
    @players_ordered = @game_session.players.order(ranking: :asc)
    @winners = @players_ordered.where(winner: true)
  end

  private

  def set_game_session
    @game_session = GameSession.find(params[:id])
  end

  def check_player_token
    @player = Player.find_by_token(session[:player_token]) if session[:player_token]
    if @player.nil?
      @player = Player.create!(game_session: @game_session)
      session[:player_token] = @player.token
    end
  end
end

app/views/game_sessions/_landing.html.erb
<div class="banner-gs" style="background: url(<%= image_path "fond.png" %>) center;">

  <div class="container" style="padding-top: 170px;">

        <p class="subtitle" style="font-family: StarJedi;">départ dans</p>

          <div class="box-counter-container">
            <span id="countdown" data-starting-at="<%= game_session.starting_at.to_i %>"
                data-next-page-path="<%= @player.next_page_path(@question) %>">
          </span>

            <div class="box-counter hours">

              <div class="box-counter one-sixtieth-second">
                <ul class="ten">
                  <li>5</li>
                  <li>4</li>
                  <li>3</li>
                  <li>2</li>
                  <li>1</li>
                  <li>0</li>
                </ul>
                <ul class="unit">
                  <li>9</li>
                  <li>8</li>
                  <li>7</li>
                  <li>6</li>
                  <li>5</li>
                  <li>4</li>
                  <li>3</li>
                  <li>2</li>
                  <li>1</li>
                  <li>0</li>
                </ul>
                <label>ms</label>
            </div>
          </div>
        </div>


        <div class="user-count">

          <div id="players_present" class="player-count"  style="background-image: url(<%= image_path "texture.jpg" %>);"  data-players-count-url="<%= players_count_game_session_path(game_session) %>">
            <h1><%= @players_count%></h1>
            <p>Joueurs</p>
          </div>

        </div>

  </div>

</div>

app/views/game_sessions/_players_present.html.erb
<%= t('.players_count', count: players_count) %>

app/views/game_sessions/_ranking.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Username</th>
    </tr>
  </thead>
  <tbody>
    <% players_ordered.each do |player| %>
      <tr>
        <th scope="row"><%= player.ranking %></th>
        <% if player.name? %>
          <td><%= player.name %></td>
        <% else %>
          <td>Inconnu</td>
        <% end  %>
      </tr>
    <tr>
    <% end %>
  </tbody>
</table>

app/views/game_sessions/_results.html.erb
<span id="ranking" data-players-ordered-url="<%= players_ordered_game_session_path(game_session) %>">
<% if game_session.closed?  %>
  <h1 style="font-family: StarJedi";> Classement Final</h1>
  <h2 style="font-family: StarJedi";>Les gagnants sont:</h2>
  <%= render 'ranking', players_ordered: winners %>
  <br>
  <h2 style="font-family: StarJedi";>Classement</h2>
<% else %>
  <h1 style="font-family: StarJedi";> Classement Provisoire</h1>
<% end %>
  <%= render 'ranking', players_ordered: players_ordered %>
</span>

app/views/game_sessions/_table.html.erb
<table class="table">
  <tr>
    <th>Cinéma</th>
    <td><%= seance.cinema.name %></td>
  <tr>
  <tr>
    <th>Film</th>
    <td><%= seance.movie %></td>
  <tr>
    <th>Séance</th>
    <td><%= l(seance.start_at, format: :long) %></td>
  </tr>
</table>

app/views/game_sessions/players_count.js.erb
document
  .getElementById("players_present")
  .innerHTML = '<%= j render "players_present", players_count: @players_count %>';

app/views/game_sessions/players_ordered.js.erb
document
  .getElementById("ranking-container")
  .innerHTML = '<%= j render "results",\
    game_session: @game_session, \
    players_ordered: @players_ordered, \
    winners: @winners %>';

app/views/game_sessions/show.html.erb
<% if (DateTime.now < @game_session.starting_at + @game_session.duration) %>
  <%= render 'landing', game_session: @game_session, seance: @seance %>
<% else %>
  <div id="ranking-container">
    <%= render 'results', game_session: @game_session, players_ordered: @players_ordered, winners: @winners %>
  </div>
<% end %>