config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'dashboard#index'

  devise_for :companies
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :game_sessions, only: [:show] do
    member do
      get '/players_count', to: 'game_sessions#players_count', as: :players_count
      get '/players_ordered', to: 'game_sessions#players_ordered', as: :players_ordered
    end
  end
  resources :players, only: [:show, :edit, :update] do
    resources :questions, only: [:show] do
      get '/countdown', to: 'questions#countdown', as: :countdown
      resources :answers, only: :create
    end
  end

  mount Attachinary::Engine => "/attachinary"
  Rails.application.routes.draw do
  # # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_banner.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,0,0,0.7) 0%, rgba(0,0,0,0.4) 50%), url( <%= image_path "banner1.jpg" %>) center;">
  <div class="banner-content">

    <p>Interagissez avec votre audience</p>

    <a class="btn btn-primary btn-lg" href="mailto:contact@7thad.eu">Demander une démo</a>


  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class= "navbar-wagon-right">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
   <% end %>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right">
    <% if company_signed_in? %>
      <!-- Avatar with dropdown menu -->
        <%= link_to "Dashboard", dashboard_path %>
      <div class="navbar-wagon-item">

        <div class="dropdown">
         <% if current_company.photo? %>
            <%= cl_image_tag current_company.photo.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
           <%= image_tag "avatar-placeholder.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
         <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_company_registration_path, method: :get do %>
                <i class="fa fa-pencil"></i>  <%= t(".update", default: "Update") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_company_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_company_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>